server.port=8080
spring.application.name=07-crud
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:crud_db;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=
spring.sql.init.encoding=UTF-8
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
